export const DarkTheme = {
  name: 'Soft Midnight Multi-Color',
  dark: true,
  colors: {
    surface: '#1e1e24',
    surfaceDim: '#16161a',
    surfaceBright: '#2a2a34',
    surfaceContainerLowest: '#121215',
    surfaceContainerLow: '#18181c',
    surfaceContainer: '#1e1e24',
    surfaceContainerHigh: '#24242c',
    surfaceContainerHighest: '#2e2e38',
    onSurface: '#e6e4df',
    onSurfaceVariant: '#a3a099',
    inverseSurface: '#e6e4df',
    inverseOnSurface: '#18181c',
    outline: '#575550',
    outlineVariant: '#383733',
    surfaceTint: '#93a5db',
    primary: '#93a5db',
    onPrimary: '#1a2544',
    primaryContainer: '#2e395c',
    onPrimaryContainer: '#d3ddf8',
    inversePrimary: '#435384',
    secondary: '#bba5d8',
    onSecondary: '#291d3d',
    secondaryContainer: '#3d3252',
    onSecondaryContainer: '#eddcfc',
    tertiary: '#88c4aa',
    onTertiary: '#102e21',
    tertiaryContainer: '#224234',
    onTertiaryContainer: '#c6ebe0',
    error: '#ea8897',
    onError: '#4a151d',
    errorContainer: '#5c232c',
    onErrorContainer: '#fcd3da',
    primaryFixed: '#e8ecf8',
    primaryFixedDim: '#c4d0f0',
    onPrimaryFixed: '#1e2847',
    onPrimaryFixedVariant: '#384878',
    secondaryFixed: '#fef4e2',
    secondaryFixedDim: '#fae3be',
    onSecondaryFixed: '#54360b',
    onSecondaryFixedVariant: '#85581b',
    tertiaryFixed: '#e0f4f5',
    tertiaryFixedDim: '#bee7e9',
    onTertiaryFixed: '#123336',
    onTertiaryFixedVariant: '#2a5b5f',
    background: '#16161a',
    onBackground: '#e6e4df',
    surfaceVariant: '#2a2a34',
  },
  typography: {
    displayLg: {
      fontFamily: 'System',
      fontSize: 48,
      fontWeight: '700',
      lineHeight: 56,
      letterSpacing: -0.02,
    },
    heroValue: {
      fontFamily: 'System',
      fontSize: 40,
      fontWeight: '700',
      lineHeight: 48,
      letterSpacing: -0.02,
    },
    headlineLg: {
      fontFamily: 'System',
      fontSize: 24,
      fontWeight: '600',
      lineHeight: 32,
      letterSpacing: -0.01,
    },
    headlineLgMobile: {
      fontFamily: 'System',
      fontSize: 20,
      fontWeight: '600',
      lineHeight: 28,
    },
    bodyMd: {
      fontFamily: 'System',
      fontSize: 16,
      fontWeight: '400',
      lineHeight: 24,
    },
    labelMd: {
      fontFamily: 'System',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 20,
      letterSpacing: 0.01,
    },
    labelSm: {
      fontFamily: 'System',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 20,
      letterSpacing: 0.01,
    },
    labelXs: {
      fontFamily: 'System',
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 16,
    },
  },
  rounded: {
    sm: 4,
    default: 6,
    md: 8,
    lg: 12,
    xl: 16,
    full: 9999,
  },
  spacing: {
    base: 8,
    containerMargin: 20,
    containerPadding: 24,
    gutter: 16,
    stackSm: 4,
    stackMd: 12,
    stackLg: 32,
    stackGap: 2,
    listItemPaddingVertical: 12,
    listItemPaddingHorizontal: 0,
    sectionPadding: 32,
    inlineGap: 8,
  },
};
