export const LightTheme = {
  name: 'Soft Pastel Multi-Color',
  dark: false,
  colors: {
    surface: '#fdfcf8',
    surfaceDim: '#efece4',
    surfaceBright: '#fffefc',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f5f2e9',
    surfaceContainer: '#ebe7dc',
    surfaceContainerHigh: '#e2ded2',
    surfaceContainerHighest: '#d7d2c4',
    onSurface: '#33302a',
    onSurfaceVariant: '#615d54',
    inverseSurface: '#33302a',
    inverseOnSurface: '#f8f6f0',
    outline: '#c9c4b5',
    outlineVariant: '#e6e2d5',
    surfaceTint: '#4a5d96',
    primary: '#435384',
    onPrimary: '#ffffff',
    primaryContainer: '#e8ecf8',
    onPrimaryContainer: '#2f3d66',
    inversePrimary: '#a6b6e4',
    secondary: '#6b588a',
    onSecondary: '#ffffff',
    secondaryContainer: '#e9e3f2',
    onSecondaryContainer: '#44355c',
    tertiary: '#3e755e',
    onTertiary: '#ffffff',
    tertiaryContainer: '#e0f0e8',
    onTertiaryContainer: '#234a3a',
    error: '#c44f62',
    onError: '#ffffff',
    errorContainer: '#fce8eb',
    onErrorContainer: '#7d2634',
    primaryFixed: '#e8ecf8',
    primaryFixedDim: '#c4d0f0',
    onPrimaryFixed: '#1e2847',
    onPrimaryFixedVariant: '#384878',
    secondaryFixed: '#fef4e2',
    secondaryFixedDim: '#fae3be',
    onSecondaryFixed: '#54360b',
    onSecondaryFixedVariant: '#85581b',
    tertiaryFixed: '#e0f4f5',
    tertiaryFixedDim: '#bee7e9',
    onTertiaryFixed: '#123336',
    onTertiaryFixedVariant: '#2a5b5f',
    background: '#f8f6f0',
    onBackground: '#33302a',
    surfaceVariant: '#ebe7dc',
  },
  typography: {
    displayLg: {
      fontFamily: 'System',
      fontSize: 48,
      fontWeight: '700',
      lineHeight: 56,
      letterSpacing: -0.02,
    },
    heroValue: {
      fontFamily: 'System',
      fontSize: 40,
      fontWeight: '700',
      lineHeight: 48,
      letterSpacing: -0.02,
    },
    headlineLg: {
      fontFamily: 'System',
      fontSize: 24,
      fontWeight: '600',
      lineHeight: 32,
      letterSpacing: -0.01,
    },
    headlineLgMobile: {
      fontFamily: 'System',
      fontSize: 20,
      fontWeight: '600',
      lineHeight: 28,
    },
    bodyMd: {
      fontFamily: 'System',
      fontSize: 16,
      fontWeight: '400',
      lineHeight: 24,
    },
    labelMd: {
      fontFamily: 'System',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 20,
      letterSpacing: 0.01,
    },
    labelSm: {
      fontFamily: 'System',
      fontSize: 14,
      fontWeight: '500',
      lineHeight: 20,
      letterSpacing: 0.01,
    },
    labelXs: {
      fontFamily: 'System',
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 16,
    },
  },
  rounded: {
    sm: 4,
    default: 6,
    md: 8,
    lg: 12,
    xl: 16,
    full: 9999,
  },
  spacing: {
    base: 8,
    containerMargin: 20,
    containerPadding: 24,
    gutter: 16,
    stackSm: 4,
    stackMd: 12,
    stackLg: 32,
    stackGap: 2,
    listItemPaddingVertical: 12,
    listItemPaddingHorizontal: 0,
    sectionPadding: 32,
    inlineGap: 8,
  },
};
